/*Autogenerated by Wandern, please add your migration SQL here.

Timestamp: 2025-08-20T19:36:38.868202

Revision ID: 68731288
Revises: acac2fb1
Message: 3rd commit


*/

-- UP

CREATE TABLE users (
    id TEXT PRIMARY KEY NOT NULL,
    email VARCHAR(255) NOT NULL
)

-- DOWN

DROP TABLE users;
