/*Autogenerated by Wandern, please add your migration SQL here.

Timestamp: 2025-08-20T19:34:51.282620

Revision ID: 723f6efb
Revises: None
Message: 1st commit
Author: Foo

*/

-- UP

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- DOWN

DROP EXTENSION IF EXISTS "uuid-ossp";
