/*Autogenerated by Wandern, please add your migration SQL here.

Timestamp: 2025-08-20T19:35:39.773580

Revision ID: acac2fb1
Revises: 723f6efb
Message: 2nd commit
Author: Foo

*/

-- UP

CREATE TABLE community (
    id TEXT PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL
)

-- DOWN

DROP TABLE community;
