MIGRATION_INIT = """/*
Autogenerated by Wandern, please add your migration SQL here.

Timestamp: {timestamp}

Revision ID: {revision_id}
Revises: {revises}
Description: {description}
*/

-- UP

-- DOWN

"""

MIGRATION_DEFAULT_TABLE_NAME = "wandern_migrations"
