MIGRATION_INIT = """/*
Autogenerated by Wandern, please add your migration SQL here.

Timestamp: {timestamp}

Revision ID: {revision_id}
Revises: {revises}
Description: {description}
*/

-- UP

-- DOWN

"""


DEFAULT_FILE_TEMPLATE = "{version}_{description}_{timestamp}.sql"
