from typing import Protocol, Any, runtime_checkable

from wandern.models import Revision


@runtime_checkable
class DatabaseMigration(Protocol):
    def create_table_migration(self) -> Any: ...

    def drop_table_migration(self) -> Any: ...

    def get_head_revision(self) -> Any | None: ...

    def migrate_up(self, revision: Revision) -> None: ...

    def migrate_down(self, revision: Revision) -> None: ...
