/*
Autogenerated by Wandern, please add your migration SQL here.

Timestamp: 2024-11-19 00:55:16

Revision ID: 0001
Revises: None
Message: create table
Tags: Foo, Bar
Author: s-bose
*/

-- UP

-- DOWN
